//
//  HomeInterfaces.swift
//  GetQuizzd
//
//  Created by Krešimir Valjevac on 26/11/2016.
//  Copyright (c) 2016 Infinum Ltd. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum HomeNavigationAction {
}

protocol HomeWireframeInterface: WireframeInterface {
    func navigate(to action: HomeNavigationAction)
}

protocol HomeViewInterface: ViewInterface {
    func showMessage(message: String)
}

protocol HomePresenterInterface: PresenterInterface {
}

protocol HomeInteractorInterface: InteractorInterface {
}
