# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GetQuizzd' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GetQuizzd
  pod 'Alamofire'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'Google/SignIn'
  pod 'Unbox'
  pod 'SwiftyJSON'
  pod 'ObjectMapper'

  target 'GetQuizzdTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
