//
//  LoginInterfaces.swift
//  GetQuizzd
//
//  Created by Krešimir Valjevac on 26/11/2016.
//  Copyright (c) 2016 Infinum Ltd. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum LoginNavigationAction {
    case Home
    case Register
}

enum LoginType {
    case Facebook
    case GooglePlus
    case Twitter
}

protocol LoginWireframeInterface: WireframeInterface {
    func navigate(to action: LoginNavigationAction, user: User)
}

protocol LoginViewInterface: ViewInterface {
    func showMessage(message: String)
}

protocol LoginPresenterInterface: PresenterInterface {
    func didPressLogin(type: LoginType)
}

protocol LoginInteractorInterface: InteractorInterface {
}
