//
//  LoginPresenter.swift
//  GetQuizzd
//
//  Created by Krešimir Valjevac on 26/11/2016.
//  Copyright (c) 2016 Infinum Ltd. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Unbox

final class LoginPresenter {

    // MARK: - Private properties -

    fileprivate weak var _view: LoginViewInterface?
    fileprivate var _interactor: LoginInteractorInterface
    fileprivate var _wireframe: LoginWireframeInterface

    // MARK: - Lifecycle -

    init (wireframe: LoginWireframeInterface, view: LoginViewInterface, interactor: LoginInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }

    func sendSocialAuthToken(socialDriver: String, token: String) {
        let url = "\(socialDriver)/authenticate/\(token)"
        
        ApiManager.sendRequest(url, .post, parameters: nil, completion: {
            data in
            
            let response: Response

            do {
                response = try unbox(data: data)
            
                let user: User = response.user
                
                KeychainManager.saveToken(token: response.token as NSString)
                
                if (user.registered == 0) {
                    self._wireframe.navigate(to: .Register, user: user)
                } else {
                    self._wireframe.navigate(to: .Home, user: user)
                }
            } catch let error {
                print(error)
            }
        }, error: {
            
        }, failure: {
        
        })
    }
}

// MARK: - Extensions -

extension LoginPresenter: LoginPresenterInterface {
    func didPressLogin(type: LoginType) {
        ApiManager.sendRequest(requestType: .FacebookLogin, view: _view as! LoginViewController!, completion: {
            result in
            
            self.sendSocialAuthToken(socialDriver: "facebook", token: result)
        }, failure: {
            error in
            
            self._view?.showMessage(message: error)
        })
    }
}
