//
//  LoginWireframe.swift
//  GetQuizzd
//
//  Created by Krešimir Valjevac on 26/11/2016.
//  Copyright (c) 2016 Infinum Ltd. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LoginWireframe: BaseWireframe {

    private let _storyboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)

    // MARK: - Module setup -

    func configureModule(with viewController: LoginViewController) {
        let interactor = LoginInteractor()
        let presenter = LoginPresenter(wireframe: self, view: viewController, interactor: interactor)
        viewController.presenter = presenter
    }

    func show(with transition: Transition, animated: Bool) {
        let moduleViewController = _storyboard.instantiateViewController(withIdentifier: "LoginViewController") as! LoginViewController
        configureModule(with: moduleViewController)

        switch transition {
        case .push:
            navigationController?.pushViewController(moduleViewController, animated: animated)
        case .present(let fromViewController):
            navigationController?.viewControllers = [moduleViewController]
            navigationController?.isNavigationBarHidden = true
            if let navigationController = navigationController {
                fromViewController.present(navigationController, animated: animated, completion: nil)
            }
        }
    }

    func _navigateToHomeScreen(user: User) {
        let homeWireframe = HomeWireframe(navigationController: navigationController!)
        homeWireframe.show(with: .push, animated: true, user: user)
    }
    
    func _navigateToRegistrationScreen(user: User) {
        let registerWireframe = RegisterWireframe(navigationController: navigationController!)
        registerWireframe.show(with: .push, animated: true, user: user)
    }
}

// MARK: - Home Wireframe Interface Requirements -

extension LoginWireframe: LoginWireframeInterface {

    func navigate(to action: LoginNavigationAction, user: User) {
        switch(action) {
        case .Home:
            _navigateToHomeScreen(user: user)
        case .Register:
            _navigateToRegistrationScreen(user: user)
        }
    }
}
