//
//  RegisterWireframe.swift
//  GetQuizzd
//
//  Created by Krešimir Valjevac on 26/11/2016.
//  Copyright (c) 2016 Infinum Ltd. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class RegisterWireframe: BaseWireframe {

    private let _storyboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)

    // MARK: - Module setup -

    func configureModule(with viewController: RegisterViewController, user: User) {
        let interactor = RegisterInteractor()
        let presenter = RegisterPresenter(wireframe: self, view: viewController, interactor: interactor)
        
        presenter.user = user
        
        viewController.presenter = presenter
    }

    func show(with transition: Transition, animated: Bool, user: User) {
        let moduleViewController = _storyboard.instantiateViewController(withIdentifier: "RegisterViewController") as! RegisterViewController
        configureModule(with: moduleViewController, user: user)

        switch transition {
        case .push:
            navigationController?.pushViewController(moduleViewController, animated: animated)
        case .present(let fromViewController):
            navigationController?.viewControllers = [moduleViewController]
            navigationController?.isNavigationBarHidden = true
            if let navigationController = navigationController {
                fromViewController.present(navigationController, animated: animated, completion: nil)
            }
        }
    }
    
    func _navigateToHomeScreen(user: User) {
        let homeWireframe = HomeWireframe(navigationController: navigationController!)
        homeWireframe.show(with: .push, animated: true, user: user)
    }
}

// MARK: - Home Wireframe Interface Requirements -

extension RegisterWireframe: RegisterWireframeInterface {

    func navigate(to action: RegisterNavigationAction) {
    }

}
