//
//  RegisterViewController.swift
//  GetQuizzd
//
//  Created by Krešimir Valjevac on 26/11/2016.
//  Copyright (c) 2016 Infinum Ltd. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class RegisterViewController: UIViewController {

    var presenter: RegisterPresenterInterface!

    @IBOutlet weak var textFieldUsername: UITextField!

    override func viewDidLoad() {
        super.viewDidLoad()
    }

    @IBAction func btnSignUpActionHandler() {
        if let nickname = textFieldUsername.text {
            if (nickname.characters.count > 0) {
                presenter.didPressSignUp(nickname: nickname)
            } else {
                self.showMessage(message: "Username cannot be emtpy.")
            }
        }
    }
}

// MARK: - Extensions -

extension RegisterViewController: RegisterViewInterface {
    func showMessage(message: String) {
        let alertView = UIAlertController(title: "GetQuizzd", message: message, preferredStyle: UIAlertControllerStyle.alert)
        alertView.addAction(UIAlertAction(title: "Ok", style: UIAlertActionStyle.default, handler: nil))
        self.present(alertView, animated: true, completion: nil)
    }
}
