//
//  RegisterInteractor.swift
//  GetQuizzd
//
//  Created by Krešimir Valjevac on 26/11/2016.
//  Copyright (c) 2016 Infinum Ltd. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class RegisterInteractor {
}

extension RegisterInteractor: RegisterInteractorInterface {
}
